apiVersion: apps/v1
kind: Deployment
metadata: 
    name: nginx123-Depolyment

spec:
    replicas: 5
    template:     
         metadata:
            labels: 
               app: test-nginx
         spec:
            containers:
             - name: nginx
               image: nginx
               ports: 
                 - containerPort: 80
    selector:
     matchLabels:
       app: test-nginx